version: '3'
services:
  cliente:
    build: ./cliente
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  chat-server:
    build: ./chat-server
    ports:
      - "5000:5000"
    depends_on:
      - server

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server-chat
      MYSQL_USER: rian
      MYSQL_PASSWORD: root9844
    ports:
      - "3307:3306"

volumes:
  mysql-data:
